package database

import (
	"log"
	"time"

	"github.com/redjackfred/voicely/backend/internal/models"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// DB set to a global variable (Singleton) for use by other packages to avoid connection leaks
var DB *gorm.DB

func ConnectDB(dsn string) {
	var err error

	// Use postgres.Open() to establish the connection, and enable logger.Info during development to see the underlying SQL generated by GORM
	DB, err = gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Info),
	})
	// Make sure to handle connection errors to prevent silent failures in the background
	if err != nil {
		log.Fatalf("Cannot connect to PostgreSQL database: %v", err)
	}

	// Get the underlying *sql.DB to configure connection pool settings
	sqlDB, err := DB.DB()
	if err != nil {
		log.Fatalf("Cannot get underlying SQL DB: %v", err)
	}

	// Implementing connection pooling best practices to ensure efficient resource management and performance under high concurrency
	sqlDB.SetMaxIdleConns(10)           // Keep a reasonable number of idle connections to handle bursts of traffic without overwhelming the database
	sqlDB.SetMaxOpenConns(100)          // Set a maximum number of open connections to prevent exhausting database resources under heavy load
	sqlDB.SetConnMaxLifetime(time.Hour) // Avoid stale connections by setting a reasonable max lifetime

	log.Println("PostgreSQL database connection and connection pool configured successfully!")

	// Execute AutoMigrate to automatically synchronize between Go Struct and database table structure
	err = DB.AutoMigrate(&models.User{}, &models.Store{}, &models.Call{})
	if err != nil {
		log.Fatalf("Database migration failed: %v", err)
	}

	log.Println("Database structure migration completed!")
}
